const CHEAT_SHEETS = {
  'algebra-1': {
    title: 'Algebra I Formula Sheet',
    sections: [
      {
        heading: 'Linear equations',
        items: [
          { label: 'Slope', formula: 'm = \\frac{y_2 - y_1}{x_2 - x_1}' },
          { label: 'Slope-intercept form', formula: 'y = mx + b' },
          { label: 'Point-slope form', formula: 'y - y_1 = m(x - x_1)' },
          { label: 'Standard form', formula: 'Ax + By = C' },
        ],
      },
      {
        heading: 'Solving',
        items: [
          { label: 'Addition property', formula: 'a = b \\Rightarrow a + c = b + c' },
          { label: 'Multiplication property', formula: 'a = b \\Rightarrow ac = bc \\ (c \\neq 0)' },
        ],
      },
      {
        heading: 'Inequalities',
        items: [
          { label: 'Flip sign when', formula: '\\text{multiply/divide by a negative number}' },
        ],
      },
    ],
  },
  geometry: {
    title: 'Geometry Formula Sheet',
    sections: [
      {
        heading: 'Area',
        items: [
          { label: 'Rectangle', formula: 'A = lw' },
          { label: 'Triangle', formula: 'A = \\frac{1}{2}bh' },
          { label: 'Circle', formula: 'A = \\pi r^2' },
          { label: 'Trapezoid', formula: 'A = \\frac{1}{2}(b_1 + b_2)h' },
        ],
      },
      {
        heading: 'Perimeter & circumference',
        items: [
          { label: 'Rectangle', formula: 'P = 2l + 2w' },
          { label: 'Circle', formula: 'C = 2\\pi r' },
        ],
      },
      {
        heading: 'Right triangles',
        items: [{ label: 'Pythagorean theorem', formula: 'a^2 + b^2 = c^2' }],
      },
    ],
  },
  'pre-calculus': {
    title: 'Pre-Calculus Formula Sheet',
    sections: [
      {
        heading: 'Unit circle',
        items: [
          { label: 'Radians', formula: '\\theta_{\\text{rad}} = \\theta_{\\text{deg}} \\cdot \\frac{\\pi}{180}' },
          { label: 'Reference angle', formula: '(\\cos\\theta, \\sin\\theta)' },
        ],
      },
      {
        heading: 'Key identities',
        items: [
          { label: 'Pythagorean', formula: '\\sin^2\\theta + \\cos^2\\theta = 1' },
          { label: 'Quotient', formula: '\\tan\\theta = \\frac{\\sin\\theta}{\\cos\\theta}' },
        ],
      },
      {
        heading: 'Quadratic',
        items: [{ label: 'Quadratic formula', formula: 'x = \\frac{-b \\pm \\sqrt{b^2-4ac}}{2a}' }],
      },
    ],
  },
}

const DEFAULT_SHEET = {
  title: 'ProvenMath Formula Sheet',
  sections: [
    {
      heading: 'General',
      items: [
        { label: 'Percent change', formula: '\\frac{\\text{new} - \\text{old}}{\\text{old}} \\times 100\\%' },
        { label: 'Average', formula: '\\bar{x} = \\frac{\\sum x_i}{n}' },
      ],
    },
  ],
}

export function getFormulaCheatSheet(courseId) {
  return CHEAT_SHEETS[courseId] ?? DEFAULT_SHEET
}

export function buildCheatSheetHtml(courseId, courseTitle) {
  const sheet = getFormulaCheatSheet(courseId)
  const title = courseTitle ? `${sheet.title} — ${courseTitle}` : sheet.title

  const sectionsHtml = sheet.sections
    .map(
      (section) => `
      <section>
        <h2>${section.heading}</h2>
        <ul>
          ${section.items
            .map(
              (item) =>
                `<li><strong>${item.label}:</strong> <span class="formula" data-formula="${escapeAttr(item.formula)}"></span></li>`,
            )
            .join('')}
        </ul>
      </section>`,
    )
    .join('')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css" />
  <style>
    body { font-family: system-ui, sans-serif; max-width: 720px; margin: 2rem auto; padding: 0 1rem; color: #1e293b; }
    h1 { font-size: 1.5rem; border-bottom: 2px solid #2563eb; padding-bottom: 0.5rem; }
    h2 { font-size: 1.1rem; margin-top: 1.5rem; color: #334155; }
    ul { list-style: none; padding: 0; }
    li { margin: 0.75rem 0; padding: 0.5rem 0; border-bottom: 1px solid #e2e8f0; }
    .footer { margin-top: 2rem; font-size: 0.75rem; color: #64748b; }
    @media print { body { margin: 1rem; } }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  ${sectionsHtml}
  <p class="footer">Generated by ProvenMath LMS — ${new Date().toLocaleDateString()}</p>
  <script src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js"><\/script>
  <script>
    document.querySelectorAll('.formula').forEach(function(el) {
      katex.render(el.dataset.formula, el, { throwOnError: false, displayMode: true });
    });
    window.onload = function() { window.print(); };
  <\/script>
</body>
</html>`
}

function escapeHtml(text) {
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function escapeAttr(text) {
  return String(text).replace(/"/g, '&quot;')
}

export function openFormulaCheatSheet(courseId, courseTitle) {
  const html = buildCheatSheetHtml(courseId, courseTitle)
  const printWindow = window.open('', '_blank')
  if (!printWindow) {
    return false
  }
  printWindow.document.write(html)
  printWindow.document.close()
  return true
}
